### PR TITLE
optional update on resize

### PR DESCRIPTION
**Pull request by vmakhaev**
Updating chart on window resize gives errors if chart is unmounted. Also in our case we want to update chart not only on window resize, but on some other events. To fix this, let's make it optional.

Another way to solve unmounted errors could be cleaning up the chart on componentWillUnmount, but I have not found a way to do it in nvd3.

### CODE REVIEW

**Comment by topicus** [comment]
@vmakhaev I've found a way to clear the windowResize event before unmount. You can check that here https://github.com/NuCivic/react-nvd3/commit/0c23f5871dc159ae131a9b508a4c5ff4b0d983f8

Let me know if that fixes the issue.

**Comment by vmakhaev** [comment]
Thanks.
It almost works. `renderChart` is called not only in `componentDidMount`, but also in `componentDidUpdate`, which overrides `resizeHandler` and prevents cleaning it up.
What is the best way to solve this?

**Comment by topicus** [comment]
Fixed. Just an if in the resize handler. https://github.com/NuCivic/react-nvd3/commit/bb6cbb3b7e31b4ebc83b96f8225b47416c5355a2

**Comment by vmakhaev** [comment]
It works. Thank you very much, again

**Comment by topicus** [comment]
Closing this. Working as expected now.

**Pull request closed without merging**
