### PR TITLE
Upgrade to react 0.14.x

### PR DESCRIPTION
**Pull request by almike**

### CODE REVIEW

**Comment by topicus** [comment]
This is great! I'm going to review it and get this in.

Thanks

**Comment by topicus** [comment]
@almike I've tested it and it works. However it would be great to have examples working in the same version. Could you update the examples to react 0.14.3?

Changing this:

```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/react-with-addons.min.js"></script>
```
By this:
```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.3/react-with-addons.min.js"></script>
```
It's enough. After this change I will get this in.

Thanks!

**Comment by almike** [comment]
hi @topicus 
got it sorted out, please check :)

**Comment by mwhite** [comment]
I'm using this library with react 0.13.x, which I can't upgrade at the moment.  Would it be possible to support both 0.13.x and >0.14 with a simple getDOMNode(refName) wrapper that does the right behavior depending on whether ref.getDOMNode() method exists?

It doesn't seem like there's a good reason to drop support for react 0.13.x just because it allows removing a couple getDOMNode() calls.

**Comment by almike** [comment]
I don't think we should add conditions to check whether a particular function exists or not...
This is a react issue, not only they break minor versions backward compatibility but they also use console.error for warnings which is an issue if you want to catch errors...
That is why many react components are dropping compatibility with react 0.13 or earlier and you are forced to use previous versions of these components; or just upgrade your react.

**Pull request merged**
